### PR TITLE
feat: syntax highlighting

### LINKED ISSUE #49: Feature request: add syntax highlighting
**Is your feature request related to a problem? Please describe.**
Adding syntax highlighting to improve ui.

**Describe the solution you'd like**
Add a new parameter to `convert` function: `highlighting` of type `boolean` with default type `false`

**Additional context**
Adding syntax highlighting using [Shiki](https://shiki.style/)

### PR DESCRIPTION
**Pull request by Jay-Karia**
Adds syntax highlighting to converted command.
Returns an html string.

API
```ts
highlight(command, theme)
```

param: `command : string`
param: `theme : "light" | "dark"` with default `"light"`

Usage
```ts
highlight("npm run dev", "dark")
```

Returns
```html
 <pre class="shiki github-dark" style="background-color:#24292e;color:#e1e4e8" tabindex="0"><code><span class="line"><span style="color:#B392F0">npm</span><span style="color:#9ECBFF"> run</span><span style="color:#9ECBFF"> dev</span></span></code></pre>
```

Closes #49

### CODE REVIEW

**Comment by bgub** [comment]
Looks good! I think it might be better as a separate function though.

**Comment by Jay-Karia** [comment]
@nebrelbug and what about #53 ?

**Comment by Jay-Karia** [comment]
Async / Await does not seem to work in rollup

async_await

It returns a `Promise` first then the html string, even after using `await`

**Comment by Jay-Karia** [comment]
jest

Problems in testing using jest.
It has some problem related to the import statement for `shiki`

**Comment by bgub** [comment]
As I'm thinking about this, I don't know if this functionality belongs in npm-to-yarn. If a user wants to display the command in a codeblock, they can add syntax highlighting with shiki themselves pretty easily.

**Comment by Jay-Karia** [comment]
It would be an add on for the library.
Can improve the asthetics of the output.

If we discontinue this, what about #60

**Comment by bgub** [comment]
I think it might be nice as a separate package to integrate.

The rest of #60 looks good to me though.

**Pull request closed without merging**
