### PR TITLE
fix: -- argument error

### LINKED ISSUE #44: pnpm conversion should remove extra `--` used to pass npm args
**Describe the bug**

Related issue: https://github.com/facebook/docusaurus/pull/9761

```bash npm2yarn
npm run swizzle @docusaurus/theme-classic Footer -- --typescript
```

This is a valid npm command, although afaik `--` isn't required by the newest npm versions, older ones still require it.

Unfortunately, the extra `--` is not supported by yarn and pnpm

The yarn conversion already removes the extra `--` but not the pnpm one:

CleanShot 2024-02-09 at 23 50 47@2x

CleanShot 2024-02-09 at 23 51 10@2x

CleanShot 2024-02-09 at 23 51 22@2x

**To Reproduce**

On any docusaurus v3.1.1 (latest version) site:

````md
```bash npm2yarn
npm run swizzle @docusaurus/theme-classic Footer -- --typescript
```
````

**Expected behavior**

Convert to:

```bash npm2yarn
pnpm run swizzle @docusaurus/theme-classic Footer --typescript
```

Instead of:

```bash npm2yarn
pnpm run swizzle @docusaurus/theme-classic Footer -- --typescript
```

**Package & Environment Details**

- Environment: macOS, Node 18, npm 10

### PR DESCRIPTION
**Pull request by OzakIOne**
https://github.com/facebook/docusaurus/pull/9761 

https://github.com/facebook/docusaurus/pull/9761#issuecomment-1936625452 

fix #44

### CODE REVIEW

**Comment by bgub** [comment]
Thanks for the PR! I just approved the tests workflow. Could you fix those that are failing?

**Comment by OzakIOne** [comment]
> Thanks for the PR! I just approved the tests workflow. Could you fix those that are failing?

Just updated the tests, all tests pass locally !

**Comment by bgub** [comment]
@OzakIOne perfect! I'll merge now.

**Comment by bgub** [comment]
@OzakIOne just published in version 2.2.0.

**Comment by OzakIOne** [comment]
> @OzakIOne just published in version 2.2.0.

I've tried version 2.2.0, I checked the source code of the lib and it doesn't have the patch included, I forgot to build the project in this PR, will make a new PR

**Comment by bgub** [comment]
@OzakIOne lol that's actually my bad, I forgot to build before releasing. I'll close your new PR if that's ok, then rebuild on my machine and publish.

**Comment by bgub** [comment]
@OzakIOne fixed in 2.2.1.

**Pull request merged**
