### PR TITLE
fix: correct issues with parsing statements

### LINKED ISSUE #6: Not sure if `npm run` is transformed correctly
**Describe the bug**

Thanks for creating a fork!

I was playing with `npm run` command. To be honest, I do not use NPM regularly, might be this is expected:

`npm run test -- --version` -> `yarn run test --version` (ok)
`npm run test -- -v` -> `yarn run test -- -v` (?)

`npm test -- --version` -> `yarn test -- --version` (?)
`npm test -- -v` -> `yarn test -- -v` (?)

Feels like `--` should be skipped in all `yarn` commands. Or did I miss something?

**Package & Environment Details**

"@armano/npm-to-yarn": "^1.1.3"

### LINKED ISSUE #7: `--save-exact` for `npm install` isn't converted correctly
**Describe the bug**
I found this fork through your contribution to Docusaurus. Seeing as the source repository appears to be dead I'm creating the issue here hoping you can fix this.

There is currently a bug with `npm install pkg --save-exact` getting converted to `yarn add pkg-exact` instead of `yarn add pkg --exact`

**To Reproduce**

1. Pass `npm install pkg --save-exact` to the npm-to-yarn with second argument set to `yarn`
2. Observe result 

**Expected behavior**
Gets converted to `yarn add pkg --exact`

**Package & Environment Details**

- Environment: Node v18.4.0
- Version: 1.1.1

**Additional context**
N.A.

### PR DESCRIPTION
**Pull request by armano2**
Changes:
- Correct shortcut `i` in npm conversion
- add support for `-D`, `-S`, `-E`, `-O` npm shortcuts
- correct issue with `rebuild` and `--force` install
- do not modify args that are part of string eg, package name `my--save-dev`
- add support for `--` in commands
- add support for `exec` commands
- correct pattern matching for `li/list`
- correct minor issue with `--exact/optional/dev`
- correct parsing `list` `--production` and `--development`
- yarn: add support for `global list`
- yarn: update conversion of `global add/remove` to reuse logic of `add/remove`
- add more test cases

fixes armano2/npm-to-yarn#7
fixes armano2/npm-to-yarn#6

### CODE REVIEW

**Comment by bgub** [comment]
@armano2 thanks so much for the PR! These are awesome changes that will make the library much more robust. My one quibble is that I think `npm unlink` should change to `yarn unlink`. Am I missing something there?

After I merge this PR, I'll add a few more tests to meet the coverage threshold and then publish a new version.

**Comment by bgub** [comment]
Also, would you be interested in being added as a maintainer?

**Comment by armano2** [comment]
> @armano2 thanks so much for the PR! These are awesome changes that will make the library much more robust. My one quibble is that I think `npm unlink` should change to `yarn unlink`. Am I missing something there?

hmm i didn't think about this use case, def we should update `unlink` and `link`

> After I merge this PR, I'll add a few more tests to meet the coverage threshold and then publish a new version.

i added alot of test cases but we are missing some, esp, for those aliases

**Comment by armano2** [comment]
@nebrelbug link/unlink added and their aliases

**Comment by bgub** [comment]
@armano2 thank you! I'll merge this now.

**Pull request merged**
