### PR TITLE
chore(docs): add setup guide

### LINKED ISSUE #52: Missing Setup Guide in README
**Problem**
There should be a setup guide in the README file with clear instructions given for local development and installing the project.

**Additional context**
The guide should include the following steps related to:
1. Installing the project.
2. Starting the project for local development.

### PR DESCRIPTION
**Pull request by Jay-Karia**
This PR adds setup guide for local development and instructions for how to test new changes made during development.

Closes #52

### CODE REVIEW

**Comment by bgub** [comment]
I'm not completely convinced that this is necessary, I think people could probably figure this out on their own.

**Comment by Jay-Karia** [comment]
It was a bit difficult for me to figure out how to test new changes made in the code, for that I had to go through Rollup docs. So I thought adding a section might help others.

This could improve DX

If you are fine without it, I am ready to close this

**Comment by bgub** [comment]
@Jay-Karia actually as I think about it, this might be helpful. Could you just rename the section to "Contributing to npm-to-yarn - Setup Guide" or something like that to clarify that it's for development of npm-to-yarn, not using npm-to-yarn?

**Comment by Jay-Karia** [comment]
@nebrelbug,
Implemented changes

**Comment by bgub** [comment]
@Jay-Karia sweet, merging now

**Pull request merged**
