### PR TITLE
feat: add `npx` conversions

### LINKED ISSUE #48: Feature request: add `npx` conversions
**Is your feature request related to a problem? Please describe.**
To convert `npx` commands to `yarn`, `pnpm`, and `bun` equivalent.

**Additional Context.**
According to me the equivalents would be:
Yarn - `yarn dlx`
Pnpm - `pnpm dlx`
Bun - `bun x`

### PR DESCRIPTION
**Pull request by Jay-Karia**
This PR adds a new type of conversions (for `npx`).

The command `npx create-next-app` is converted into:
`yarn dlx create-next-app` (yarn)
`pnpm dlx create-next-app` (pnpm)
`bun x create-next-app` (bun)

Automatically detects executor commands and converts it

Here's a code example.

```ts
convert("npx create-next-app", "yarn");
// yarn dlx create-next-app
```

Closes #48

### CODE REVIEW

**Comment by Jay-Karia** [comment]
@nebrelbug should I add tests before merging ?

**Comment by bgub** [comment]
@Jay-Karia Yeah tests would be great, thanks

**Comment by bgub** [comment]
@slorber, I'd love to hear your thoughts about this proposal since Docusaurus is one of the main users of npm-to-yarn.

**Comment by Jay-Karia** [comment]
https://github.com/facebook/docusaurus/issues/10355

**Comment by slorber** [comment]
Yes that looks like a useful feature to add that we could use on the Docusaurus website

**Comment by bgub** [comment]
@Jay-Karia I think for ease of use, it should detect whether or not it is an executor command (test for `npx|pnpm dlx|...`) automatically rather than requiring an extra argument flag.

**Comment by Jay-Karia** [comment]
@nebrelbug Should we consider updating the version to: `2.3.0` or `3.0.0` after this feature?

**Comment by Jay-Karia** [comment]
@nebrelbug Removed extra argument

**Comment by lishaduck** [comment]
pnpm uses `pnpmx` and Bun uses `bunx` shorthands, which are both shorter and easier to remember, though there have been bugs with the shims not getting installed in the past. Don't know about yarn.

**Comment by Jay-Karia** [comment]
`bunx` has bugs in windows.
`pnpmx` does not exists, it's either `pnpm exec` or `pnpm dlx`. Same goes with `yarn`

**Comment by lishaduck** [comment]
> `bunx` has bugs in windows.

Ah, didn't know that. I only use it on macOS.

> `pnpmx` does not exists, it's either `pnpm exec` or `pnpm dlx`.

Sorry, typo. I meant `pnpx`. Apparently they deprecated it though, so I guess it still still stands that you should use `pnpm dlx`.

**Comment by bgub** [comment]
@Jay-Karia thanks for the great work! I think we should probably update to a major version. Do you think this is ready to merge?

**Comment by Jay-Karia** [comment]
Yes

**Comment by bgub** [comment]
I just merged this (with the CLI, not through the web client) and released in https://github.com/nebrelbug/npm-to-yarn/releases/tag/v3.0.0! Thanks for your help!

**Comment by slorber** [comment]
Note: that's a bit unfortunate but it looks like `yarn dlx` is not supported by Yarn 1

For this reason the limits the adoption of this feature. I don't think it's a good idea to use it on the Docusaurus website because many users use Yarn 1 (including ourselves)

**Comment by Jay-Karia** [comment]
is `yarn exec` supported in Yarn 1 ?

**Comment by slorber** [comment]
I don't see it listed here: https://classic.yarnpkg.com/en/docs/cli/

However `yarn exec echo "Hello"` works but it doesn't seem to be a decent alternative to npx

**Pull request closed without merging**
